version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: expense-tracker-app
    container_name: expense-tracker-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - expense-tracker-db
    networks:
      - laravel-network
    environment:
      DB_HOST: expense-tracker-db
      DB_PORT: 3306
      DB_DATABASE: expense_tracker
      DB_USERNAME: newuser
      DB_PASSWORD: password

  expense-tracker-db:
    image: mysql:8.0
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: expense_tracker
      MYSQL_USER: newuser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laravel-network

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan schedule:work
    volumes:
      - .:/var/www
    depends_on:
      - expense-tracker-db
    networks:
      - laravel-network

  npm_server:
    build:
        context: .
        dockerfile: Dockerfile
    command: npm run dev
    volumes:
        - .:/var/www
    depends_on:
        - expense-tracker-db
    networks:
        - laravel-network
    ports:
        - "5173:5173" 

volumes:
  mysql-data:

networks:
  laravel-network:
